//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// hps_mfc_sandbox.rc で使用
//
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MAINFRAME_2                 129
#define IDR_hps_mfc_sandboxTYPE         130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_VIEW_CONFIGURATIONS          304
#define ID_VIEW_TABBED_BROWSER          305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define ID_VIEW_MODELBROWSER            308
#define ID_VIEW_PROPERTIES              309
#define ID_VIEW_SEGMENTBROWSER          310
#define IDB_OPERATORS_LARGE             311
#define IDC_SEGMENT_TREE                311
#define IDB_OPERATORS_SMALL             312
#define IDB_LARGE_ICON                  313
#define IDB_SMALL_ICON                  314
#define IDD_PROGRESS                    315
#define IDB_PNG1                        316
#define IDC_ROOT_COMBO_BOX              317
#define IDB_PROPERTIES_CHECK_BOX        318
#define IDB_SEGMENT_BROWSER             319
#define IDB_APPLY_PROPERTIES_EDIT       320
#define IDB_MODEL_BROWSER_BEGIN         360
#define IDB_MB_UNKNOWN                  360
#define IDB_MODEL_FILE                  361
#define IDB_PRODUCT_STRUCTURE_1         362
#define IDB_PRODUCT_STRUCTURE_2         363
#define IDB_RI_SOLID                    364
#define IDB_RI_SURFACE                  365
#define IDB_RI_PLANE                    366
#define IDB_RI_LINE                     367
#define IDB_RI_ARC                      368
#define IDB_RI_COMP_CURVE               369
#define IDB_RI_CURVE                    370
#define IDB_RI_POINT                    371
#define IDB_RI_POINT_CLOUD              372
#define IDB_RI_DIRECTION                373
#define IDB_RI_COORD_SYS                374
#define IDB_RI_GEOMETRY_SET             375
#define IDB_VIEW                        376
#define IDB_ANNOTATION_VIEW             377
#define IDB_VIEW_GROUP                  378
#define IDB_PMI_TEXT                    379
#define IDB_PMI_TOLERANCE               380
#define IDB_PMI_DIM_DISTANCE            381
#define IDB_PMI_DIM_LENGTH              382
#define IDB_PMI_DIM_RADIUS              383
#define IDB_PMI_DIM_DIAMETER            384
#define IDB_PMI_DIM_ANGLE               385
#define IDB_PMI_DATUM                   386
#define IDB_PMI_DATUM_TARGET            387
#define IDB_PMI_ROUGHNESS               388
#define IDB_PMI_CIRCLE_CENTER           389
#define IDB_PMI_LINE_WELDING            390
#define IDB_PMI_SPOT_WELDING            391
#define IDB_PMI_BALLOON                 392
#define IDB_PMI_COORDINATE              393
#define IDB_PMI_FASTENER                394
#define IDB_PMI_LOCATOR                 395
#define IDB_PMI_MEASUREMENT_POINT       396
#define IDB_PMI_ARROW                   397
#define IDB_PMI_TABLE                   398
#define IDB_PMI_GROUP                   399
#define IDB_DRW_MODEL                   400
#define IDB_DRW_SHEET                   401
#define IDB_DRW_VIEW                    402
#define IDB_DRW_VIEW_BACK               403
#define IDB_DRW_VIEW_BACKGROUND         404
#define IDB_DRW_VIEW_BOTTOM             405
#define IDB_DRW_VIEW_DETAIL             406
#define IDB_DRW_VIEW_FRONT              407
#define IDB_DRW_VIEW_ISO                408
#define IDB_DRW_VIEW_LEFT               409
#define IDB_DRW_VIEW_RIGHT              410
#define IDB_DRW_VIEW_SECTION            411
#define IDB_DRW_VIEW_TOP                412
#define IDB_MODEL_BROWSER_END           412
#define IDR_MENU1                       413
#define IDR_MB_CONTEXT_MENU             413
#define IDD_PDF_EXPORT_DIALOG           414
#define IDD_EXCHANGE_IMPORT_DIALOG      415
#define IDR_SB_CONTEXT_MENU             416
#define IDD_BLEND_DIALOG                417
#define IDD_CREATE_SOLID_DIALOG         419
#define IDD_DELETE_FACE_DIALOG          421
#define IDD_HOLLOW_DIALOG               423
#define IDD_FR_DIALOG                   425
#define IDD_DELETE_COMP_DIALOG          427
#define IDD_BOOLEAN_DIALOG              429
#define IDD_MIRROR_DIALOG               431
#define IDC_PROGRESS_BAR                1000
#define IDC_BUTTON_CANCEL               1001
#define IDC_MODEL_BROWSER               1002
#define IDC_CONFIGURATION_TREE          1003
#define IDC_RADIO_2D                    1003
#define IDC_RADIO_3D                    1004
#define IDC_EDIT_MESSAGES               1007
#define IDC_IMPORT_MESSAGE              1008
#define IDC_CHECK_KEEP_OPEN             1009
#define IDC_EDIT_BLEND_R                1010
#define IDC_EDIT_XL                     1011
#define IDC_EDIT_YL                     1012
#define IDC_EDIT_ZL                     1013
#define IDC_EDIT_OX                     1014
#define IDC_EDIT_OY                     1015
#define IDC_EDIT_OZ                     1016
#define IDC_EDIT_DX                     1017
#define IDC_EDIT_DY                     1018
#define IDC_EDIT_DZ                     1019
#define IDC_STATIC_XL                   1020
#define IDC_STATIC_YL                   1021
#define IDC_STATIC_ZL                   1022
#define IDC_RADIO_BLOCK                 1023
#define IDC_RADIO_CYLINDER              1024
#define IDC_EDIT_T                      1025
#define IDC_EDIT_SEL_CNT                1028
#define IDC_BUTTON_CLEAR                1030
#define IDC_EDIT_CEL_CNT                1032
#define IDC_LIST_PS_TAG                 1034
#define IDC_LIST1                       1036
#define IDC_LIST_FR_DETECTED            1036
#define IDC_LIST_BODY_TAG               1036
#define IDC_RADIO_FR_BOSS               1037
#define IDC_RADIO_FR_CONCENTRIC         1038
#define IDC_RADIO_FR_COPLANAR           1039
#define IDC_EDIT_FR_SEL                 1040
#define IDC_EDIT_FR_DETECT              1041
#define IDC_STATIC_COMP                 1043
#define IDC_CHECK_HOLLOW_OUTSIDE        1044
#define IDC_RADIO_UNITE                 1045
#define IDC_RADIO_SUBTRACT              1046
#define IDC_RADIO_INTERSECT             1047
#define IDC_LIST_BOOL_TOOL              1048
#define IDC_EDIT_BOOL_TARGET            1049
#define IDC_EDIT_TARGET                 1050
#define IDC_EDIT_MIRROR_PLANE           1051
#define IDC_EDIT_MIRROR_XL              1052
#define IDC_EDIT_MIRROR_YL              1053
#define IDC_EDIT_MIRROR_XV              1055
#define IDC_EDIT_MIRROR_YV              1056
#define IDC_EDIT_MIRROR_ZV              1057
#define IDC_EDIT_MIRROR_ZL              1058
#define IDC_CHECK_MIRROR_COPY           1059
#define IDC_CHECK_MIRROR_MERGE          1060
#define IDC_RADIO_SPRING                1061
#define IDC_COMBO_SOLID_TYPE            1062
#define IDC_STATIC_TYPE                 1063
#define IDC_RADIO_BLEND_TYPE_R          1064
#define IDC_RADIO_BLEND_TYPE_C          1065
#define IDC_EDIT_BLEND_C2               1066
#define IDC_CHECK_CHAMFER_FLIP          1067
#define IDC_STATIC_BLEND_C2             1068
#define IDC_STATIC_BLEND_R              1069
#define IDC_RADIO_SPHERE                1070
#define IDC_EDIT_CB                     1073
#define IDC_RADIO_CONE                  1074
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_OPERATORS_SELECT_POINT       32771
#define ID_OPERATORS_SELECT_AREA        32772
#define ID_OPERATORS_ORBIT              32773
#define ID_OPERATORS_PAN                32774
#define ID_OPERATORS_ZOOM_AREA          32775
#define ID_OPERATORS_ZOOM_FIT           32776
#define ID_OPERATORS_HOME               32777
#define ID_MODES_SIMPLE_SHADOW          32778
#define ID_MODES_SMOOTH                 32779
#define ID_MODES_HIDDEN_LINE            32780
#define ID_MODES_EYE_DOME_LIGHTING      32781
#define ID_USER_CODE_1                  32782
#define ID_USER_CODE_2                  32783
#define ID_USER_CODE_3                  32784
#define ID_USER_CODE_4                  32785
#define ID_MODES_FRAME_RATE             32786
#define ID_MB_CONTEXT_SHOW_HIDE         32787
#define ID_OPERATORS_FLY                32788
#define ID_MB_CONTEXT_ISOLATE           32789
#define ID_MB_CONTEXT_RESET_VISIBILITY  32790
#define ID_OPERATOR_SEGMENT_BROWSER     32791
#define ID_OPERATOR_MODEL_BROWSER       32792
#define ID_DWGLAYER_TURNON              32798
#define ID_DWGLAYER_TOGGLE              32799
#define ID_COMBO_SEL_LEVEL              32800
#define ID_ADDATTRIBUTE_MATERIAL        32802
#define ID_ADDATTRIBUTE_CAMERA          32803
#define ID_ADDATTRIBUTE_MODELLINGMATRIX 32804
#define ID_ADDATTRIBUTE_TEXTUREMATRIX   32805
#define ID_ADDATTRIBUTE_CULLING         32806
#define ID_ADDATTRIBUTE_CURVEATTRIBUTE  32807
#define ID_ADDATTRIBUTE_CYLINDERATTRIBUTE 32808
#define ID_ADDATTRIBUTE_EDGEATTRIBUTE   32809
#define ID_ADDATTRIBUTE_LIGHTINGATTRIBUTE 32810
#define ID_ADDATTRIBUTE_LINEATTRIBUTE   32811
#define ID_ADDATTRIBUTE_MARKERATTRIBUTE 32812
#define ID_ADDATTRIBUTE_SURFACEATTRIBUTE 32813
#define ID_ADDATTRIBUTE_SELECTABILITY   32814
#define ID_ADDATTRIBUTE_SPHEREATTRIBUTE 32815
#define ID_ADDATTRIBUTE_SUBWINDOW       32816
#define ID_ADDATTRIBUTE_TEXTATTRIBUTE   32817
#define ID_ADDATTRIBUTE_TRANSPARENCY    32818
#define ID_ADDATTRIBUTE_VISIBILITY      32819
#define ID_ADDATTRIBUTE_VISUALEFFECTS   32820
#define ID_ADDATTRIBUTE_PERFORMANCE     32821
#define ID_ADDATTRIBUTE_DRAWINGATTRIBUTE 32822
#define ID_ADDATTRIBUTE_HIDDENLINEATTRIBUTE 32823
#define ID_ADDATTRIBUTE_MATERIALPALETTE 32824
#define ID_ADDATTRIBUTE_CONTOURLINE     32825
#define ID_ADDATTRIBUTE_CONDITION       32826
#define ID_ADDATTRIBUTE_BOUNDING        32827
#define ID_ADDATTRIBUTE_ATTRIBUTELOCK   32828
#define ID_ADDATTRIBUTE_TRANSFORMMASK   32829
#define ID_ADDATTRIBUTE_COLORINTERPOLATION 32830
#define ID_ADDATTRIBUTE_CUTTINGSECTIONATTRIBUTE 32831
#define ID_ADDATTRIBUTE_PRIORITY        32832
#define ID_ATTRIBUTECONTEXTMENU_UNSET   32833
#define ID_BUTTON_FR_BOSS               32834
#define ID_BUTTON_FR_CONCENTRIC         32835
#define ID_BUTTON_FR_COPLANAR           32836
#define ID_BUTTON_BOOL                  32839
#define ID_BUTTON_DELETE_FACE           32842
#define ID_BUTTON_HOLLOW                32843
#define ID_BUTTON_FR                    32844
#define ID_BUTTON_DELETE_BODY           32845
#define ID_BUTTON_MIRROR                32846

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        435
#define _APS_NEXT_COMMAND_VALUE         32848
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
